mysql_root_password: 'vagrant'

php_version: '5.6'

php_upload_max_filesize: '16M'
php_max_file_uploads: '20'
php_memory_limit: '128M'
php_error_reporting: 'E_ALL & ~E_DEPRECATED & ~E_STRICT'
php_post_max_size: '16M'

php_modules:
  - "php5"
  - "php5-cli"
  - "php5-mysql"
  - "php5-gd"
  - "php5-imagick"
  - "php5-curl"
  - "php5-intl"
  - "libapache2-mod-php5"

apache_vhosts:
  site1:
    vhost_docroot: '/var/www/test_site1'
    vhost_name: 'site1.dev'
    vhost_options: 'All'
  site2:
    vhost_docroot: '/var/www/test_site2'
    vhost_name: 'site2.dev'
    vhost_options: 'All'

mysql_db:
  db_site1:
    db_name: 'db_site1'
    db_user: 'vagrant'
    db_password: 'vagrant'
  db_site2:
    db_name: 'db_site2'
    db_user: 'vagrant'
    db_password: 'vagrant'
